---
abstract: 'A multi-file version of Data::NDS::Multiele'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-NDS-Multifile
provides:
  Data::NDS::Multifile:
    file: lib/Data/NDS/Multifile.pm
    version: 3.12
requires:
  Data::NDS: 0
  Data::NDS::Multiele: 0
  Storable: 0
  YAML::Syck: 0
  perl: 5.001
resources:
  license: http://dev.perl.org/licenses/
version: 3.12
