---
name: Data-NDS-Multifile
version: 3.10
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: A multi-file version of Data::NDS::Multiele
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::NDS: 0
  Data::NDS::Multiele: 0
  Storable: 0
  YAML::Syck: 0
  perl: 5.6.0
provides:
  Data::NDS::Multifile:
    file: lib/Data/NDS/Multifile.pm
    version: 3.10
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
