perl -I../lib add_ele.hash.t 1
perl -I../lib add_ele.list.t 1
perl -I../lib copy_hash.t 1
perl -I../lib copy_list.t 1
perl -I../lib default_element.hash.t 1
perl -I../lib default_element.list.t 1
perl -I../lib delete_ele.hash.t 1
perl -I../lib delete_ele.list.t 1
perl -I../lib ele.hash.t 1
perl -I../lib ele.list.t 1
perl -I../lib eles.hash.t 1
perl -I../lib eles.list.t 1
perl -I../lib file.hash.error.t 1
perl -I../lib file.hash.t 1
perl -I../lib file.list.error.t 1
perl -I../lib file.list.t 1
perl -I../lib is_default_value.hash.t 1
perl -I../lib keys.t 1
perl -I../lib path_in_use.t 1
perl -I../lib path_valid.t 1
perl -I../lib path_values.hash.t 1
perl -I../lib path_values.list.t 1
perl -I../lib rename_ele.hash.t 1
perl -I../lib update_ele.t 1
perl -I../lib value.t 1
perl -I../lib values.t 1
perl -I../lib which.hash.t 1
perl -I../lib which.list.t 1
